CarlifoniaHealthWeb/ViewModels/ConsultantCalendar.cs
namespace CarliforniaHealthWeb.ViewModels;

public class ConsultantCalendar
{
    public int Id { get; set; }

    public int? ConsultantId { get; set; }

    public DateTime? Date { get; set; }

    public bool? Available { get; set; }
}

CarlifoniaHealthWeb/Pages/Account.cshtml.cs
using Auth0.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CarlifoniaHealthWeb.Pages;

public class AccountModel : PageModel
{
    public void OnGet()
    {
    }

    public async Task OnGetLogin()
    {
        // Indicate here where Auth0 should redirect the user after a login.
        // Note that the resulting absolute Uri must be added to the
        // **Allowed Callback URLs** settings for the app.
        var authenticationProperties = new LoginAuthenticationPropertiesBuilder()
            .WithRedirectUri("/")
            .Build();

        await HttpContext.ChallengeAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
    }

   
    public async Task OnGetLogout()
    {
        var authenticationProperties = new LogoutAuthenticationPropertiesBuilder()
            // Indicate here where Auth0 should redirect the user after a logout.
            // Note that the resulting absolute Uri must be added to the
            // **Allowed Logout URLs** settings for the app.
            .WithRedirectUri(Url.Page("Index"))
            .Build();

        await HttpContext.SignOutAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    }
}

CarlifoniaHealthWeb/Pages/ConsultantCalendarView.cshtml.cs
using System.Text.Json;
using CarlifoniaHealthWeb.ViewModels;
using CarliforniaHealthWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CarlifoniaHealthWeb.Pages;

public class ConsultantCalendarViewModel : PageModel
{
    private readonly HttpClient _consultantsServiceClient;
    private readonly HttpClient _calendarServiceClient;
    private readonly ILogger<ConsultantCalendarViewModel> _logger;

    public ConsultantCalendarViewModel(IHttpClientFactory httpClientFactory, ILoggerFactory loggerFactory)
    {
        _consultantsServiceClient = httpClientFactory.CreateClient("ConsultantsService");
        _calendarServiceClient = httpClientFactory.CreateClient("CalendarService");

        _logger = loggerFactory.CreateLogger<ConsultantCalendarViewModel>();
    }

    [BindProperty(SupportsGet = true)]
    public int Id { get; set; }
    public Consultant? SelectedConsultant { get; set; }

    public IReadOnlyCollection<AppointmentViewModel> ConsultantSchedule { get; set; } = new List<AppointmentViewModel>();
    public AppointmentViewModel? Result { get; set; }
    public string? Error { get; set; }


    public async Task OnGet()
    {
        await LoadConsultant();
        await LoadConsultantCalendar();
    }

    public async Task OnPostBookAppointment(DateTime appointmentDate)
    {
        _logger.LogInformation("Attempting to book an appointment  on {0:dd-mm-yyyy}", appointmentDate);

        var response = await _calendarServiceClient.PostAsJsonAsync("/appointments", new
        {
            AppointmentDate = appointmentDate,
            ConsultantId = Id,
            PatientId = User?.Identity?.Name?.GetHashCode() ?? 1// Request.HttpContext.TraceIdentifier.GetHashCode()
        });
        var responseContent = await response.Content.ReadAsStringAsync();

        if (response.IsSuccessStatusCode)
        {
            var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
            Result = JsonSerializer.Deserialize<AppointmentViewModel>(responseContent, options);

            _logger.LogInformation("Appointment booked {@Result}", Result);
        }
        else
        {
            _logger.LogWarning("Failed to secure appointment");
            var problemDetails = JsonSerializer.Deserialize<ProblemDetails>(responseContent);
            Error = problemDetails?.Detail ?? "Failed to secure appointment, please try again later";
        }
    }

    private async Task LoadConsultantCalendar()
    {
        _logger.LogInformation("Fetching calendar for consultant {@Id}", Id);

        try
        {
            var results = await _calendarServiceClient.GetFromJsonAsync<IReadOnlyCollection<AppointmentViewModel>>($"/appointments?consultantId={Id}");
            _logger.LogInformation("Consultant Appointments: {@Results}", results);
            ConsultantSchedule = results!;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to load consultant calendar");
        }
    }

    private async Task LoadConsultant()
    {
        _logger.LogInformation("Fetching consultant details for ID {@Id}", Id);
        try
        {
            SelectedConsultant = await _consultantsServiceClient.GetFromJsonAsync<Consultant>($"/consultants/{Id}");
            _logger.LogInformation("Consultant: {@SelectedConsultant}", SelectedConsultant);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to load consultant");
        }
    }
}

CarlifoniaHealthWeb/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CarlifoniaHealthWeb.Pages;
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

CarlifoniaHealthWeb/Pages/Index.cshtml.cs
using System.Reflection.Metadata;
using System.Reflection;
using CarlifoniaHealthWeb.ViewModels;
using CarliforniaHealthWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CarlifoniaHealthWeb.Pages;
public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly HttpClient _httpClient;

    public IndexModel(IHttpClientFactory httpClientFactory, ILogger<IndexModel> logger)
    {
        _logger = logger;
        _httpClient = httpClientFactory.CreateClient("ConsultantsService");
    }

    public IReadOnlyCollection<Consultant> Consultants { get; set; } = new List<Consultant>();

    public async Task OnGet()
    {
        _logger.LogInformation("Fetching consultants...");
        try
        {
            var consultants = await _httpClient.GetFromJsonAsync<IReadOnlyCollection<Consultant>>("/consultants");
            _logger.LogInformation("Consultants: {@Consultants}", consultants);
            Consultants = consultants ?? new List<Consultant>();
        }
        catch (HttpRequestException ex) when (ex.StatusCode != System.Net.HttpStatusCode.InternalServerError)
        {
            _logger.LogWarning("Cannot retrieve consultants at the moment", ex);
        }
    }

    public IActionResult OnPostViewConsultant(int consultantId)
    {
        _logger.LogInformation("Redirecting to consultant view");
        return RedirectToPage("ConsultantCalendarView", new { id = consultantId });
    }
}

CarlifoniaHealthWeb/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CarlifoniaHealthWeb.Pages;
public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

CarlifoniaHealthWeb/Pages/Account.cshtml
@page
@model CarlifoniaHealthWeb.Pages.AccountModel
@{
}

CarlifoniaHealthWeb/Pages/ConsultantCalendarView.cshtml
@page "{id:int}"
@model ConsultantCalendarViewModel

@{
    ViewData["Title"] = "Book appointment";
}
<h4>Consultant Details</h4>

<h5>@Model.SelectedConsultant?.FirstName @Model.SelectedConsultant?.LastName</h5>

<form class="container" method="post" asp-page-handler="BookAppointment">
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Appointment Date</label>
                <input type="date" class="form-control" name="appointmentDate" required/>
            </div>

            <div class="list-group">
                @foreach (var appointment in Model.ConsultantSchedule)
                {
                    <div class="list-group-item">
                        @appointment.StartDate.ToString("d")
                    </div>
                }
            </div>
        </div>

        <div class="col-6">
            <div class="card">
                <img src=@($"/img/doctor{Model.Id}.jpg") class="card-img" alt=""/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="d-flex">
                <button type="submit" class="btn btn-primary">
                    Submit
                </button>
            </div>
        </div>
    </div>

    @if (Model.Result != null)
    {
        <div class="row">
            <div class="col">
                <div class="w-100 border rounded border-success px-5 py-2">
                    <h4 class="text-dark">Appointment has been booked successfully</h4>
                    <dl>
                        <dd>Date</dd>
                        <dl>@Model.Result.StartDate.ToString("d")</dl>
                    </dl>
                </div>
            </div>
        </div>
    }
    @if (Model.Error != null)
    {
        <div class="row">
            <div class="col">
                <div class="w-100 border rounded border-warning px-5 py-2">
                    <h4 class="text-dark">Failed to book appointment</h4>
                    <dl>
                        <dd>Date</dd>
                        <dl>@Model.Error</dl>
                    </dl>
                </div>
            </div>
        </div>
    }
</form>

CarlifoniaHealthWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<!--service-->
<section id="service" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <h2 class="ser-title">Our Service</h2>
                <hr class="botm-line">
                <p>Our world-renowned medical and surgical consultants have a broad range of experience and expertise, enabling them to treat conditions from the straightforward to the incredibly complex.</p>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-stethoscope"></i>
                    </div>
                    <div class="icon-info">
                        <h4>24 Hour Support</h4>
                        <p>
                            Our hospitals have Urgent Care Centres available across London so you can access immediate care.
                            We provide urgent care services for adults over 18 and an Urgent Care Centre for children under 18 at The Portland Hospital..
                        </p>
                    </div>
                </div>
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-ambulance"></i>
                    </div>
                    <div class="icon-info">
                        <h4>Emergency Services</h4>
                        <p>
                            Our hospitals have Urgent Care Centres available across London so you can access immediate care.
                            We provide urgent care services for adults over 18 and an Urgent Care Centre for children under 18 at The Portland Hospital..
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-user-md"></i>
                    </div>
                    <div class="icon-info">
                        <h4>Medical Counseling</h4>
                        <p>We are investing in, and helping to develop, some of the world’s most innovative treatments – making the previously untreatable, treatable..</p>
                    </div>
                </div>
                <div class="service-info">
                    <div class="icon">
                        <i class="fa fa-medkit"></i>
                    </div>
                    <div class="icon-info">
                        <h4>Premium Healthcare</h4>
                        <p>We are investing in, and helping to develop, some of the world’s most innovative treatments – making the previously untreatable, treatable..</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ service-->
<!--doctor team-->
<section id="doctor-team" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="ser-title">Meet Our Doctors!</h2>
                <hr class="botm-line">
            </div>
            @if (Model.Consultants.Any())
            {
                int i = 0;
                foreach (var consultant in Model.Consultants)
                {
                    i++;
                    <div class="col-md-3 col-sm-3 col-xs-6">
                        <div class="thumbnail">
                            <img src=@($"img/doctor{i}.jpg") alt="..." class="team-img">
                            <div class="caption">
                                <h3 class>@consultant.FirstName </h3>
                                <p>@consultant.Speciality</p>
                                <ul class="list-inline">
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="w-100">
                                <form method="post" asp-page-handler="ViewConsultant" class="d-flex flex-column align-items-center justify-content-center">
                                    <input name="consultantId" type="hidden" value="@consultant.Id">
                                    <button class="btn btn-dark" type="submit">
                                        Appointment
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>
<!--/ doctor team-->
<!--contact-->
<section id="contact" class="section-padding mt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="ser-title">Contact us</h2>
                <hr class="botm-line">
            </div>
            <div class="col-md-4 col-sm-4">
                <h3 class="text-muted">Contact Info</h3>
                <div class="space"></div>
                <p><i class="fa fa-map-marker fa-fw pull-left fa-2x"></i>321 Awesome Street<br> New York, NY 17022</p>
                <div class="space"></div>
                <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x"></i>info@californianhealth.com</p>
                <div class="space"></div>
                <p><i class="fa fa-phone fa-fw pull-left fa-2x"></i>+1 800 123 1234</p>
            </div>
            <div class="col-md-8 col-sm-8 marb20">
                <div class="contact-info">
                    <h3 class="cnt-ttl">Having Any Query! Or Book an appointment</h3>
                    <div class="space"></div>
                    <div id="sendmessage">Your message has been sent. Thank you!</div>
                    <div id="errormessage"></div>
                    <form action="" method="post" role="form" class="contactForm">
                        <div class="form-group">
                            <input type="text" name="name" class="form-control br-radius-zero" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control br-radius-zero" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control br-radius-zero" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                            <div class="validation"></div>
                        </div>
                        <div class="form-group">
                            <textarea class="form-control br-radius-zero" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                            <div class="validation"></div>
                        </div>

                        <div class="form-action">
                            <button type="submit" class="btn btn-form">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ contact-->